USE penjualan;

ALTER TABLE menu
  MODIFY COLUMN harga INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN modal INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE transaksi
  MODIFY COLUMN harga INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN modal INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN subtotal INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN laba INT NOT NULL DEFAULT 0;

